### ISSUE TITLE
ChangedMC appears to be unstable when you install new mods, and can cause a renderthread CTD

### ISSUE THREAD

**Issue by TheSystemGuy1337** [LtxProgrammer/Changed-Minecraft-Mod#1046]
Here we go again. Recently, I have found out the hard way that ChangedMC appears to be rather volatile when it comes to mod installations. If you have existing mods, ChangedMC seems to get along well. But adding new mods (ie Video Player) will cause it to become unstable and will crash Minecraft if you try to start it. I don't know what could be causing this, and it all started with [this issue I made.](https://github.com/Foxyas/Changed-Addon-Rework/issues/16). The crash occurs during the transition from the loading screen to the title screen or Forge error screen. Instead of the fadeout animation playing, Minecraft crashes with a Render Thread error.

BUT, If I install my mods one-by-one (install mod, start Minecraft, close Minecraft, rinse and repeat), then this crash does not occur.

I'm not a programmer or a very good one, but I think this might be some IRQ conflict like issue. Here is the debugging log from MultiMC:

[debug.log](https://github.com/user-attachments/files/17087866/debug.log)

**Comment by gengyoubo** [comment]
This is where I think the problem arises:
[20:00:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.8 by Oracle Corporation
[20:00:00] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/TheSystemGuy/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20:00:01] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[20:00:01] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'watermedia', Requested by: 'videoplayer', Expected range: '[2.0,)', Actual version: '[MISSING]'
[20:00:02] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[20:00:02] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2, --gameDir, C:\Users\TheSystemGuy\MultiMC\instances\1.18.2\.minecraft, --assetsDir, C:\Users\TheSystemGuy\MultiMC\assets, --uuid, <PROFILE ID>, --username, TheSystemGuy, --assetIndex, 1.18, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[20:00:02] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[20:00:02] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[20:00:02] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[20:00:02] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[20:00:07] [pool-3-thread-1/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `changed` for name `deferred_state_provider`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[20:00:07] [pool-3-thread-1/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `changed` for name `mixed_state_provider`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[20:00:09] [Render thread/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/C:/Users/TheSystemGuy/MultiMC/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2371!/assets/.mcassetsroot' uses unexpected schema
[20:00:09] [Render thread/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/C:/Users/TheSystemGuy/MultiMC/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2371!/data/.mcassetsroot' uses unexpected schema
[20:00:09] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:00:10] [Render thread/INFO] [minecraft/Minecraft]: Setting user: TheSystemGuy
[20:00:10] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[20:00:11] [Render thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod Â§evideoplayerÂ§r requires Â§6watermediaÂ§r Â§o2.0 or aboveÂ§r
Â§7Currently, Â§6watermediaÂ§rÂ§7 is Â§oÂ§nnot installed
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.18.2-40.2.0.jar%2372!/:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:95) ~[fmlcore-1.18.2-40.2.0.jar%2372!/:?] {}
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:127) ~[fmlcore-1.18.2-40.2.0.jar%2372!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.2.0-universal.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.0-universal.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.2.0-universal.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.18.2-20220404.173914-srg.jar%2371!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2371!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc5.jar:mmc5] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[20:00:11] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state

**Comment by gengyoubo** [comment]
`[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod 文件 C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar 缺少 mods.toml 文件
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod 文件 C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar 缺少 mods.toml 文件
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod 文件 C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar 缺少 mods.toml 文件
[20:00:01] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod 文件 C:\Users\TheSystemGuy\MultiMC\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar 缺少 mods.toml 文件
[20:00:01] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: 未找到要加载的依赖项。跳过！
[20:00:01] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: 缺少或不支持强制依赖项：
Mod ID：“watermedia”，请求者：“videoplayer”，预期范围：“[2.0,)”，实际版本：“[MISSING]” `
This module became that way around version 1.18.2, may I suggest you find a replacement or get help to make a new one?

**Comment by gengyoubo** [comment]
What I'm trying to tell you is that even if you manage to launch the game, by the time you play the video it will flash back and be bad. I highly discourage the use of this mod!

**Comment by gengyoubo** [comment]
If you can give me an open source file ......

**Comment by TheSystemGuy1337** [comment]
> What I'm trying to tell you is that even if you manage to launch the game, by the time you play the video it will flash back and be bad. I highly discourage the use of this mod!

I did install Watermedia after this; and the crash reappeared, but installing them one-by-one fixes them. Since you discourage use of that mod (I only really wanted to try it out), I will discontinue use of that mod immediately and just move it to it's own install on MultiMC.

However, even with a handful of mods, the crash can still occur. This is the very first instance of this crash. The actual error is identical, which is `java.lang.IllegalArgumentException: No model for layer changed:dark_latex_wolf_partial#main`

[FirstCrashdebug.log](https://github.com/user-attachments/files/17088103/FirstCrashdebug.log)

**Comment by LtxProgrammer** [comment]
> However, even with a handful of mods, the crash can still occur. This is the very first instance of this crash. The actual error is identical, which is `java.lang.IllegalArgumentException: No model for layer changed:dark_latex_wolf_partial#main`

Please see #943

**Comment by TheSystemGuy1337** [comment]
> Please see #943
I did take a look at it. The fix for me is simply wipe the .config folder, and install the mods one by one. Since you folks are well aware of the issue, I am preemptively closing the issue to not drag you down the rabbit hole any further. But a message should be added in the readme advising to do what I did to *maybe* fix the issue instead of filing a bug report.

Closing.
