### ISSUE TITLE
Unsupported forge version 40.2.26

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1216]
Not sure why this is happening, just know that forge version 40.2.26 is not compatible anymore ......
![image](https://github.com/user-attachments/assets/6fcf94ba-90de-48e7-8481-6311700d3729)
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getServiceProviders(ThreadContextDataInjector.java:83)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.initServiceProviders(ThreadContextDataInjector.java:73)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getProviders(ThreadContextDataInjector.java:285)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.access$000(ThreadContextDataInjector.java:55)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector$ForCopyOnWriteThreadContextMap.<init>(ThreadContextDataInjector.java:226)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createDefaultInjector(ContextDataInjectorFactory.java:94)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createInjector(ContextDataInjectorFactory.java:71)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ReusableLogEventFactory.<init>(ReusableLogEventFactory.java:42)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.LoggerConfig.<clinit>(LoggerConfig.java:96)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:136)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:76)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by gengyoubo** [comment]
This seems to be unique to this version, 40.2.25 doesn't have it ......

**Comment by LtxProgrammer** [comment]
Not a Changed issue.
