### ISSUE TITLE
Cannot work on the server无法在服务器上运行[mohist/cat server]

### ISSUE THREAD

**Issue by Pisces-Moze** [LtxProgrammer/Changed-Minecraft-Mod#1218]
我使用最新的模组无法在我的服务器上工作
我的服务器上只有这个模组
The latest mod cannot work on the server
 I only have this mod on the server
 Error log
```
[02:41:02] [main/WARN]: Mod file /media/minecraft/D4F47AEFF47AD36A/server/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.18/fmlcore-1.18.2-40.2.18.jar is missing mods.toml file
[02:41:02] [main/WARN]: Mod file /media/minecraft/D4F47AEFF47AD36A/server/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.18/javafmllanguage-1.18.2-40.2.18.jar is missing mods.toml file
[02:41:02] [main/WARN]: Mod file /media/minecraft/D4F47AEFF47AD36A/server/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.18/lowcodelanguage-1.18.2-40.2.18.jar is missing mods.toml file
[02:41:02] [main/WARN]: Mod file /media/minecraft/D4F47AEFF47AD36A/server/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.18/mclanguage-1.18.2-40.2.18.jar is missing mods.toml file
[02:41:02] [main/INFO]: No dependencies to load found. Skipping!
[02:41:03] [main/INFO]: Compatibility level set to JAVA_17
[02:41:03] [main/INFO]: Launching target 'forgeserver' with arguments []
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
        ... 5 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.18/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at TRANSFORMER/forge@40.2.18/net.minecraftforge.registries.GameData.init(GameData.java:123)
        at TRANSFORMER/forge@40.2.18/net.minecraftforge.registries.GameData.<clinit>(GameData.java:108)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:407)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:391)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:170)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:133)
        ... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector efficientFoodExhaustion(Lnet/minecraft/world/entity/player/Player;F)V in changed.mixins.json:entity.PlayerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap changed.refmap.json
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 38 more
```

**Comment by gengyoubo** [comment]
好像是mixin的问题

**Comment by gengyoubo** [comment]
你是不是缺服务器的插件了？

**Comment by bzmid** [comment]
> 你是不是缺服务器的插件了？

插件？不需要插件吧

**Comment by hhdsjgit** [comment]
I'm also getting the same error, which prevents my server from updating the mod
我也一样无法在服务器上运行.（catserver1.18.2）

**Comment by LtxProgrammer** [comment]
So the server wont let you update the mod, because the old version of the mod wont load?

**Comment by hhdsjgit** [comment]
No, because when using changed-mc 0.14 mod, the server will report an error and cannot be started.

**Comment by bzmid** [comment]
I built Changed-mc0.14c myself. But it still cannot run ;(

**Comment by hhdsjgit** [comment]
不是还不能运行?是不是FORGE版本太低了?

**Comment by LtxProgrammer** [comment]
> I built Changed-mc0.14c myself. But it still cannot run ;(

Do you have a full `latest.log` for this?

**Comment by strelkies** [comment]
i built v0.14c myself after having this problem as well, still unable to start a server.
[latest.log](https://github.com/user-attachments/files/18089443/latest.log)

**Comment by cecnull1** [comment]
我也一样，我在开发环境启动Server都不能成功

**Comment by hhdsjgit** [comment]
我用catserver用changed0.14c可以正常运行,报错特别多而已

**Comment by LtxProgrammer** [comment]
> i built v0.14c myself after having this problem as well, still unable to start a server. [latest.log](https://github.com/user-attachments/files/18089443/latest.log)

Log extract:
```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.digest.DigestUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at gg.essential.loader.stage1.EssentialLoaderBase.getChecksum(EssentialLoaderBase.java:356) ~[?:?]
	at gg.essential.loader.stage1.EssentialLoaderBase.downloadFile(EssentialLoaderBase.java:473) ~[?:?]
	at gg.essential.loader.stage1.EssentialLoaderBase.doDownload(EssentialLoaderBase.java:326) ~[?:?]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:176) ~[?:?]
	at gg.essential.loader.stage1.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:46) ~[?:?]
	at gg.essential.loader.stage1.EssentialTransformationService.<init>(EssentialTransformationService.java:29) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	...
```

This looks like a missing dependency. Make sure you aren't missing anything, and create a new issue if you can't fix it.

**Comment by LtxProgrammer** [comment]
Initial error log indicates a similar issue to #1224. fe2a5199a7ffc17a09e7fdf0cb556c6c3ffb01f4 Should fix this issue.
