### ISSUE TITLE
Game crashes on booting up with diffrent mods

### ISSUE THREAD

**Issue by Garlakel** [LtxProgrammer/Changed-Minecraft-Mod#183]
Error:
Game crashes on startup

Crash report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/12/23, 2:58 PM
Description: Rendering overlay

java.lang.IllegalAccessError: class net.minecraft.client.resources.model.ModelBakery tried to access private field net.minecraft.client.renderer.block.model.multipart.Selector.f_112015_ (net.minecraft.client.resources.model.ModelBakery and net.minecraft.client.renderer.block.model.multipart.Selector are in module minecraft@1.18.2 of loader 'TRANSFORMER' @4d4436d0)
  at net.minecraft.client.resources.model.ModelBakery.mdd23e1e$lambda$overWriteMultiPart$7$7(ModelBakery.java:749) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
  at net.minecraft.client.resources.model.ModelBakery.overWriteMultiPart(ModelBakery.java:701) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.resources.model.ModelBakery.handler$zke000$loadTopLevel(ModelBakery.java:828) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:501) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.resources.model.ModelBakery.lambda$processLoading$8(ModelBakery.java:189) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2330!/:?] {re:mixin}
  at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:188) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:changed.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:61) ~[forge-1.18.2-40.1.85-universal.jar%23120!/:?] {re:classloading}
  at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,re:classloading}
  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:changed.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
  Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
  at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:changed.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
  at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
  at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.85.jar%2319!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%237!/:?] {}
  at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
  at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) [proxyserver.jar:2.12.3] {}
  at crystallauncher.MineClient.start(MineClient.java:228) [proxyserver.jar:2.12.3] {}
  at crystallauncher.MineClient.main(MineClient.java:36) [proxyserver.jar:2.12.3] {}

-- Last reload --
Details:
  Reload number: 1
  Reload reason: initial
  Finished: No
  Packs: Default

-- System Details --
Details:
  Minecraft Version: 1.18.2
  Minecraft Version ID: 1.18.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 17.0.1, Microsoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
  Memory: 1715009720 bytes (1635 MiB) / 3422552064 bytes (3264 MiB) up to 6408896512 bytes (6112 MiB)
  CPUs: 8
  Processor Vendor: GenuineIntel
  Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Identifier: Intel64 Family 6 Model 158 Stepping 9
  Microarchitecture: Kaby Lake
  Frequency (GHz): 2.81
  Number of physical packages: 1
  Number of physical CPUs: 4
  Number of logical CPUs: 8
  Graphics card #0 name: Intel(R) HD Graphics 630
  Graphics card #0 vendor: Intel Corporation (0x8086)
  Graphics card #0 VRAM (MB): 1024.00
  Graphics card #0 deviceId: 0x591b
  Graphics card #0 versionInfo: DriverVersion=22.20.16.4708
  Graphics card #1 name: NVIDIA GeForce GTX 1050
  Graphics card #1 vendor: NVIDIA (0x10de)
  Graphics card #1 VRAM (MB): 4095.00
  Graphics card #1 deviceId: 0x1c8d
  Graphics card #1 versionInfo: DriverVersion=27.21.14.6677
  Memory slot #0 capacity (MB): 8192.00
  Memory slot #0 clockSpeed (GHz): 2.40
  Memory slot #0 type: DDR4
  Memory slot #1 capacity (MB): 8192.00
  Memory slot #1 clockSpeed (GHz): 2.67
  Memory slot #1 type: DDR4
  Virtual memory max (MB): 24624.11
  Virtual memory used (MB): 14377.29
  Swap memory total (MB): 8320.00
  Swap memory used (MB): 90.59
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6092M -Xms1024M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Launched Version: 1.18.2-forge-40.1.85
  Backend library: LWJGL version 3.2.2 SNAPSHOT
  Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 466.77, NVIDIA Corporation
  Window size: 854x480
  GL Caps: Using framebuffer using OpenGL 3.2
  GL debug messages: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'forge'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla
  Current Language: English (US)
  CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  ModLauncher: 9.1.3+9.1.3+main.9b69c82a
  ModLauncher launch target: forgeclient
  ModLauncher naming: srg
  ModLauncher services: 
     mixin PLUGINSERVICE 
     eventbus PLUGINSERVICE 
     slf4jfixer PLUGINSERVICE 
     object_holder_definalize PLUGINSERVICE 
     runtime_enum_extender PLUGINSERVICE 
     capability_token_subclass PLUGINSERVICE 
     accesstransformer PLUGINSERVICE 
     runtimedistcleaner PLUGINSERVICE 
     mixin TRANSFORMATIONSERVICE 
     fml TRANSFORMATIONSERVICE 
  FML Language Providers: 
    minecraft@1.0
    lowcodefml@null
    kotlinforforge@3.7.1
    javafml@null
  Mod List: 
    client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
    forge-1.18.2-40.1.85-universal.jar                |Forge                         |forge                         |40.1.85             |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jankomag\AppData\Roaming\Crystal-Launcher\instances\u.B.U.L.S.H.I.D\.minecraft\crash-reports\crash-2023-01-12_14.58.36-client.txt

I am aware that the problem causing this may be on my side, but this is still a major bug, causing crash on load of the game, please fix ASAP.

Oh I also used turned patch but it does not seem to influence the result.

Ask me on discord for more details:
Garłak#4588

**Comment by LtxProgrammer** [comment]
use forge 40.2.0
