### ISSUE TITLE
black latex infect dirt_path cause the game crashed

### ISSUE THREAD

**Issue by fcrhiaxpk** [LtxProgrammer/Changed-Minecraft-Mod#317]
I found a bug. If the black latex infected the "dirt_path" block it will cause the game crash. I use the HMCL launcher to play minecraft. Here is my crash report. I hope it can be fixed :)
[minecraft-exported-crash-info-2023-02-25T14-54-05.zip](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/10830493/minecraft-exported-crash-info-2023-02-25T14-54-05.zip)

**Comment by fcrhiaxpk** [comment]
I don't know if other launcher will have this bug, but I will report anyway

**Comment by fcrhiaxpk** [comment]
I tested more about this bug and found that only if you turn on the “Better Grass” option in the Quallty Settings and let the infectied block show its side ，In this case, the game will crash. So this bug seems unimportant？

**Comment by LtxProgrammer** [comment]
Issue is from better grass option in Optifine.

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023/2/25 下午2:53
Description: Tesselating block model

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.m_6840_(net.minecraft.world.level.block.state.BlockState, net.minecraft.core.Direction, java.util.Random)" because "net.optifine.BetterGrass.modelDirtPath" is null
	at net.optifine.BetterGrass.getFaceQuadsDirtPath(BetterGrass.java:358) ~[OptiFine-1.18.2_HD_U_H9_pre2.jar%2378!/:?] {re:classloading}
	at net.optifine.BetterGrass.getFaceQuads(BetterGrass.java:277) ~[OptiFine-1.18.2_HD_U_H9_pre2.jar%2378!/:?] {re:classloading}
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:58) ~[OptiFine-1.18.2_HD_U_H9_pre2.jar%2378!/:?] {re:classloading}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelSmooth(ModelBlockRenderer.java:152) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:107) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:88) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:1108) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:924) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

```
-- Block model being tesselated --
Details:
	Block: Block{minecraft:dirt_path}[covered_with=neutral]
	Block location: World: (23,66,33), Section: (at 7,2,1 in 1,4,2; chunk contains blocks 16,-64,32 to 31,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:107) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:88) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:1108) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:924) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

The game crashing block is a non-covered `minecraft:dirt_path`
