### ISSUE TITLE
Current version is incompatible with optifine

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#477]
Crashes when attempting to render a latex covered block.

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2774
	at net.optifine.render.MultiTextureBuilder.build(MultiTextureBuilder.java:64) ~[preview_OptiFine_1.18.2_HD_U_H9_pre2.jar%2375!/:?] {re:classloading}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85721_(BufferBuilder.java:392) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?] {re:computing_frames,xf:OptiFine:default,re:classloading,xf:OptiFine:default}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at it.unimi.dsi.fastutil.objects.ObjectArraySet$Spliterator.forEachRemaining(ObjectArraySet.java:289) ~[fastutil-8.5.6.jar%2341!/:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:1140) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:924) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by LtxProgrammer** [comment]
Oh well, Rubidium + Oculus make a good replacement.

**Comment by Y1rd** [comment]
I don't even use optifine either, but for some reason the transfur progress isn't visible on players if you do use Rubidium. Unless that was fixed while I've playing other games.
Something to do with #392 which was closed.
