### ISSUE TITLE
Crash when using Oculus and TConstruct

### ISSUE THREAD

**Issue by AbsoluteJuicer** [LtxProgrammer/Changed-Minecraft-Mod#486]
Mods: 
- changed 0.12
- rubidium 0.5.6
- oculus 1.5.4
- mantle 1.9.45
- tconstruct 3.6.4

Forge version: 40.2.9
How to trigger: crashes upon launching
did not happen when using changed alone, changed + oculus, changed + tconstruct, tconstruct + oculus
also did not crash when using changed 0.11.3 + oculus + tconstruct

Suspicion: the bakeAll() method in LatexCoveredBlocks might have caused it

Stack Trace:

> [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.client.event.ModelBakeEvent@5dd54856 dispatch for modid changed
java.lang.IllegalStateException: BlockModel parent has to be a block model.
	at net.minecraft.client.renderer.block.model.BlockModel.m_5500_(BlockModel.java:161) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.client.renderer.block.model.MultiVariant.m_111857_(MultiVariant.java:61) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.client.renderer.block.model.MultiVariant.m_5500_(MultiVariant.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.ltxprogrammer.changed.client.LatexCoveredBlocks$Registrar.lambda$bakeAll$1(LatexCoveredBlocks.java:253) ~[Changed-m1.18.2-v0.12.jar%2377!/:v0.12]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.ltxprogrammer.changed.client.LatexCoveredBlocks$Registrar.bakeAll(LatexCoveredBlocks.java:251) ~[Changed-m1.18.2-v0.12.jar%2377!/:v0.12]
	at net.ltxprogrammer.changed.client.LatexCoveredBlocks$ModEvents.onModelBake(LatexCoveredBlocks.java:402) ~[Changed-m1.18.2-v0.12.jar%2377!/:v0.12]
	at net.minecraftforge.eventbus.ASMEventHandler_1262_ModEvents_onModelBake_ModelBakeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.9.jar%23212!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23211!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.2.9.jar%23211!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.2.9.jar%23211!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:443) ~[forge-1.18.2-40.2.9-universal.jar%23215!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5787_(ModelManager.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5787_(ModelManager.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?]

**Comment by AbsoluteJuicer** [comment]
update: after pulling the newest changes from github, it no longer crashes at start up. However, it still crashes upon entering a world.

Stack Trace: 

> java.lang.IllegalStateException: Illegal render type!
	at net.coderbot.iris.pipeline.WorldRenderingPhase.fromTerrainRenderType(WorldRenderingPhase.java:43) ~[oculus-mc1.18.2-1.6.4.jar%2356!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.LevelRenderer.handler$zcl000$iris$beginTerrainLayer(LevelRenderer.java:7200) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zle000$postRenderLayer(LevelRenderer.java:10042) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:5623) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.invokeRenderChunkLayer(LevelRenderer.java) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:442) ~[oculus-mc1.18.2-1.6.4.jar%2356!/:?] {re:mixin,re:classloading}
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1026) ~[oculus-mc1.18.2-1.6.4.jar%2356!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zcl000$iris$renderTerrainShadows(LevelRenderer.java:7124) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1150) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinLevelRenderer_EntityListSorting,pl:mixin:APP:rubidium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:mixins.oculus.json:LevelRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:fabulous.MixinDisableFabulousGraphics,pl:mixin:APP:mixins.oculus.json:shadows.MixinLevelRenderer,pl:mixin:APP:mixins.oculus.json:sky.MixinLevelRenderer_SunMoonToggle,pl:mixin:APP:mixins.oculus.fantastic.json:MixinLevelRenderer,pl:mixin:APP:mixins.oculus.compat.sodium.json:sky.MixinLevelRenderer,pl:mixin:APP:changed.mixins.json:render.LevelRendererMixin,pl:mixin:APP:mixins.oculus.json:shadows.MixinPreventRebuildNearInShadowPass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:changed.mixins.json:render.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:changed.mixins.json:render.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by LtxProgrammer** [comment]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/106349281/f475f805-8fc6-418e-994c-1376674d2a79)
Crash occurs in the above code. (WorldRenderingPhase.class : oculus)
