### ISSUE TITLE
Game crashes when show player model whie transfured as the white tiger added in 13.1

### ISSUE THREAD

**Issue by Alphawolf1890** [LtxProgrammer/Changed-Minecraft-Mod#867]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/22/24, 6:04 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'void dev.tr7zw.notenoughanimations.logic.PlayerTransformer.preUpdate(net.minecraft.client.player.AbstractClientPlayer, net.minecraft.client.model.PlayerModel, float, org.spongepowered.asm.mixin.injection.callback.CallbackInfo)'
	at net.ltxprogrammer.changed.client.renderer.animate.LatexAnimator.handler$bbj000$setupAnimHEAD(LatexAnimator.java:533) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading,pl:mixin:APP:changed.compatibility.mixins.json:NotEnoughAnimations.LatexAnimatorMixin,pl:mixin:A}
	at net.ltxprogrammer.changed.client.renderer.animate.LatexAnimator.setupAnim(LatexAnimator.java) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading,pl:mixin:APP:changed.compatibility.mixins.json:NotEnoughAnimations.LatexAnimatorMixin,pl:mixin:A}
	at net.ltxprogrammer.changed.client.renderer.model.LatexWhiteTigerModel.setupAnim(LatexWhiteTigerModel.java:143) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:classloading}
	at net.ltxprogrammer.changed.client.renderer.model.LatexWhiteTigerModel.m_6973_(LatexWhiteTigerModel.java:17) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:classloading}
	at net.ltxprogrammer.changed.client.FormRenderHandler.lambda$renderHand$1(FormRenderHandler.java:75) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.ltxprogrammer.changed.process.ProcessTransfur.ifPlayerLatex(ProcessTransfur.java:371) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading}
	at net.ltxprogrammer.changed.client.FormRenderHandler.renderHand(FormRenderHandler.java:49) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$bbg001$renderHand(PlayerRenderer.java:2541) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_117775_(PlayerRenderer.java) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_117770_(PlayerRenderer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109346_(ItemInHandRenderer.java:239) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:339) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:778) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ltxprogrammer.changed.client.renderer.animate.LatexAnimator.handler$bbj000$setupAnimHEAD(LatexAnimator.java:533) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading,pl:mixin:APP:changed.compatibility.mixins.json:NotEnoughAnimations.LatexAnimatorMixin,pl:mixin:A}
	at net.ltxprogrammer.changed.client.renderer.animate.LatexAnimator.setupAnim(LatexAnimator.java) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading,pl:mixin:APP:changed.compatibility.mixins.json:NotEnoughAnimations.LatexAnimatorMixin,pl:mixin:A}
	at net.ltxprogrammer.changed.client.renderer.model.LatexWhiteTigerModel.setupAnim(LatexWhiteTigerModel.java:143) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:classloading}
	at net.ltxprogrammer.changed.client.renderer.model.LatexWhiteTigerModel.m_6973_(LatexWhiteTigerModel.java:17) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:classloading}
	at net.ltxprogrammer.changed.client.FormRenderHandler.lambda$renderHand$1(FormRenderHandler.java:75) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.ltxprogrammer.changed.process.ProcessTransfur.ifPlayerLatex(ProcessTransfur.java:371) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,re:classloading}
	at net.ltxprogrammer.changed.client.FormRenderHandler.renderHand(FormRenderHandler.java:49) ~[Changed-m1.18.2-v0.13.1.jar%2365!/:v0.13.1] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$bbg001$renderHand(PlayerRenderer.java:2541) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_117775_(PlayerRenderer.java) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_117770_(PlayerRenderer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:getarmpose,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:getarmpose,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109346_(ItemInHandRenderer.java:239) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:339) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:runtimedistcleaner:A,re:classloading,xf:fml:voidscape:evaluatewhichhandstorender,xf:fml:voidscape:selectionusingitemwhileholdingbowlike,xf:fml:voidscape:ischargedcrossbow,xf:fml:voidscape:renderarmwithitem,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:tac.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:changed.mixins.json:render.ItemInHandRendererMixin,pl:mixin:APP:firstperson.mixins.json:HeldItemRendererMixin,pl:mixin:APP:notenoughanimations.mixins.json:ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:778) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Alphawolf1890'/352, l='ClientLevel', x=1033.52, y=62.11, z=-311.65]]
	Chunk stats: 841, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 52053 game time, 33487 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:changed.mixins.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23113!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by LtxProgrammer** [comment]
Error seems to be an incompatible version of NEA, try using a different version

**Comment by LtxProgrammer** [comment]
While also being unrelated to white tiger
