### ISSUE TITLE
Players disconnect due to server error if a transfurred player is leashed using the Leashed mod.

### ISSUE THREAD

**Issue by J0w03L** [LtxProgrammer/Changed-Minecraft-Mod#925]
## Problem

Like the title says, if the server has the "Leashed" (https://www.curseforge.com/minecraft/mc-mods/leashed) mod installed, attempting to leash a transfurred player will cause everyone to disconnect from the server with the reason "Internal server error". This appears to be an issue with Leashed, not this mod, and thus this issue is intended more as an incompatibility report than a bug.

## Steps to reproduce

1. Setup and run a Forge `40.2.0` dedicated server with the `Changed-m1.18.2-v0.13.1.jar` and `leashed-1.18.1-1.2.3.jar ` (from https://www.curseforge.com/minecraft/mc-mods/leashed/files/3614245) mods installed.
2. Have two or more players join the server.
3. Transfur a player into a form of your choosing.
4. Have another player leash them with the "Diamond Lead" item from Leashed mod.
5. Observe that all players are immediately disconnected with "Internal server error" stated as the reason.

## Relevant logs
(please note that there were additional mods installed here at the time of these logs being created, however the issue should be replicable with any setup containing this mod and Leashed.)

### Server

```
[04Jun2024 20:00:31.081] [User Authenticator #26/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player J0w03L is <censored>
[04Jun2024 20:00:34.026] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@36597483[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:37608) lost connection: Disconnected
[04Jun2024 20:00:37.226] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@3f1f4d1[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:37618) lost connection: Disconnected
[04Jun2024 20:00:41.276] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@79d425c9[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:36518) lost connection: Disconnected
[04Jun2024 20:00:45.781] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@b8fb9f
[04Jun2024 20:00:45.790] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: J0w03L[/xxx.xxx.xxx.xxx:37594] logged in with entity id 91517 at (255.91462339741727, 20.0, -625.0536997249819)
[04Jun2024 20:00:45.802] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: J0w03L joined the game
[04Jun2024 20:00:45.802] [Server thread/INFO] [tac/]: PENDING
[04Jun2024 20:00:45.802] [Server thread/INFO] [net.ltxprogrammer.changed.Changed/]: Player joined, setting enabling update checker flag
[04Jun2024 20:00:45.802] [Thread-2/INFO] [net.ltxprogrammer.changed.Changed/]: Checking for updates
[04Jun2024 20:00:46.434] [Server thread/INFO] [de.melanx.simplebackups.SimpleBackups/]: Backup done.
[04Jun2024 20:00:46.553] [SimpleBackups/INFO] [de.melanx.simplebackups.BackupThread/]: Successfully deleted "world_2024-06-02_22-34-57.zip"
[04Jun2024 20:00:46.654] [Server thread/WARN] [net.minecraft.world.level.chunk.LevelChunk/]: Block entity sophisticatedbackpacks:backpack @ BlockPos{x=195, y=20, z=-637} state Block{sophisticatedbackpacks:copper_backpack}[battery=false,covered_with=neutral,facing=west,left_tank=false,right_tank=false,waterlogged=false] invalid for ticking:
[04Jun2024 20:00:59.486] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@775f6e66[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:38572) lost connection: Disconnected
[04Jun2024 20:01:03.286] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@5f106bd6[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:38592) lost connection: Disconnected
[04Jun2024 20:06:47.637] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@6d6fc68a[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:51588) lost connection: Disconnected
[04Jun2024 20:06:55.937] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@265476a2[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:51602) lost connection: Disconnected
[04Jun2024 20:10:38.989] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@17af9702[id=<null>,name=iiJ0w03L,properties={},legacy=false] (/xxx.xxx.xxx.xxx:56490) lost connection: Disconnected
[04Jun2024 20:15:48.250] [User Authenticator #27/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player iiJ0w03L is <censored>
[04Jun2024 20:16:17.587] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Disconnecting com.mojang.authlib.GameProfile@2378f62e[id=<censored>,name=iiJ0w03L,properties={textures=[com.mojang.authlib.properties.Property@334a45fd]},legacy=false] (/xxx.xxx.xxx.xxx:34474): Took too long to log in
[04Jun2024 20:16:17.588] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@2378f62e[id=<censored>,name=iiJ0w03L,properties={textures=[com.mojang.authlib.properties.Property@334a45fd]},legacy=false] (/xxx.xxx.xxx.xxx:34474) lost connection: Took too long to log in
[04Jun2024 20:16:17.637] [Server thread/WARN] [net.minecraft.network.Connection/]: handleDisconnection() called twice
[04Jun2024 20:26:01.514] [User Authenticator #28/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player iiJ0w03L is <censored>
[04Jun2024 20:26:21.786] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@41cd41df
[04Jun2024 20:26:21.791] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: iiJ0w03L[/xxx.xxx.xxx.xxx:49964] logged in with entity id 95012 at (251.69999998807907, 38.543398002371816, -625.0835978150081)
[04Jun2024 20:26:21.801] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: iiJ0w03L joined the game
[04Jun2024 20:26:21.801] [Server thread/INFO] [tac/]: PENDING
[04Jun2024 20:26:21.801] [Server thread/INFO] [net.ltxprogrammer.changed.Changed/]: Player joined, setting enabling update checker flag
[04Jun2024 20:26:21.801] [Thread-2/INFO] [net.ltxprogrammer.changed.Changed/]: Checking for updates
[04Jun2024 20:27:58.738] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        Index: 23
        Listeners:
                0: NORMAL
                1: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfurProgress onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfurForm onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                3: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfur onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class net.foxyas.changedaddon.procedures.UntransfurProgressProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class net.foxyas.changedaddon.procedures.TickPlayerAreinDuctProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: class net.foxyas.changedaddon.procedures.TickHazardArmorFeatureProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class net.foxyas.changedaddon.procedures.SmalltickupdateProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: class net.foxyas.changedaddon.procedures.MusicPlayerProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class net.foxyas.changedaddon.procedures.LatexSolventOnEffectActiveTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class net.foxyas.changedaddon.procedures.LatexResistancetickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class net.foxyas.changedaddon.procedures.LatexInfectionTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class net.foxyas.changedaddon.procedures.GrabEscapeNeedClicksProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class net.foxyas.changedaddon.procedures.GrabeffectTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: class net.foxyas.changedaddon.procedures.GiveHazyPurpleAdvabcementProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class net.foxyas.changedaddon.procedures.GetPainiteArmorWithProtectionProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class net.foxyas.changedaddon.procedures.GetfullpainitearmorprocedureProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class net.foxyas.changedaddon.procedures.FightTokeepyourconsciousnessProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class net.foxyas.changedaddon.procedures.DolatexinfectiontickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class com.tac.guns.common.ReloadTracker onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class com.tac.guns.common.DiscardOffhand onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: class com.tac.guns.common.AimingManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: class com.minecolonies.coremod.event.EventHandler onEnteringChunk(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class plutosion.leashed.handler.LeadHandler leadBreaking(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class net.ltxprogrammer.changed.entity.variant.LatexVariantInstance onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class net.ltxprogrammer.changed.block.WhiteLatexTransportInterface$EventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: net.minecraftforge.eventbus.EventBus$$Lambda$1517/0x000000030160cf08@640b0be4
                27: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@56646bb7 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        at TRANSFORMER/leashed@1.2.3/plutosion.leashed.handler.LeadHandler.leadBreaking(LeadHandler.java:81)
        at net.minecraftforge.eventbus.ASMEventHandler_312_LeadHandler_leadBreaking_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.2.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:874)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:208)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:245)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:840)

[04Jun2024 20:27:58.773] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /xxx.xxx.xxx.xxx:37594
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        at plutosion.leashed.handler.LeadHandler.leadBreaking(LeadHandler.java:81) ~[leashed-1.18.1-1.2.3.jar%2352!/:1.2.3]
        at net.minecraftforge.eventbus.ASMEventHandler_312_LeadHandler_leadBreaking_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:874) ~[forge-1.18.2-40.2.0-universal.jar%2376!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:208) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        ... 9 more
[04Jun2024 20:27:58.775] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        Index: 23
        Listeners:
                0: NORMAL
                1: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfurProgress onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfurForm onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                3: ASM: class net.foxyas.changedaddon.process.CheckPlayerTransfur onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class net.foxyas.changedaddon.procedures.UntransfurProgressProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class net.foxyas.changedaddon.procedures.TickPlayerAreinDuctProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: class net.foxyas.changedaddon.procedures.TickHazardArmorFeatureProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class net.foxyas.changedaddon.procedures.SmalltickupdateProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: class net.foxyas.changedaddon.procedures.MusicPlayerProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class net.foxyas.changedaddon.procedures.LatexSolventOnEffectActiveTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class net.foxyas.changedaddon.procedures.LatexResistancetickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class net.foxyas.changedaddon.procedures.LatexInfectionTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class net.foxyas.changedaddon.procedures.GrabEscapeNeedClicksProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class net.foxyas.changedaddon.procedures.GrabeffectTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: class net.foxyas.changedaddon.procedures.GiveHazyPurpleAdvabcementProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class net.foxyas.changedaddon.procedures.GetPainiteArmorWithProtectionProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class net.foxyas.changedaddon.procedures.GetfullpainitearmorprocedureProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class net.foxyas.changedaddon.procedures.FightTokeepyourconsciousnessProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class net.foxyas.changedaddon.procedures.DolatexinfectiontickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class com.tac.guns.common.ReloadTracker onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class com.tac.guns.common.DiscardOffhand onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: class com.tac.guns.common.AimingManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: class com.minecolonies.coremod.event.EventHandler onEnteringChunk(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class plutosion.leashed.handler.LeadHandler leadBreaking(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class net.ltxprogrammer.changed.entity.variant.LatexVariantInstance onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class net.ltxprogrammer.changed.block.WhiteLatexTransportInterface$EventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: net.minecraftforge.eventbus.EventBus$$Lambda$1517/0x000000030160cf08@640b0be4
                27: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@56646bb7 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        at TRANSFORMER/leashed@1.2.3/plutosion.leashed.handler.LeadHandler.leadBreaking(LeadHandler.java:81)
        at net.minecraftforge.eventbus.ASMEventHandler_312_LeadHandler_leadBreaking_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.2.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:874)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:208)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:245)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:840)

[04Jun2024 20:27:58.803] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /xxx.xxx.xxx.xxx:49964
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class net.minecraft.world.entity.Mob (net.minecraft.server.level.ServerPlayer and net.minecraft.world.entity.Mob are in module minecraft@1.18.2 of loader 'TRANSFORMER' @291373d3)
        at plutosion.leashed.handler.LeadHandler.leadBreaking(LeadHandler.java:81) ~[leashed-1.18.1-1.2.3.jar%2352!/:1.2.3]
        at net.minecraftforge.eventbus.ASMEventHandler_312_LeadHandler_leadBreaking_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:874) ~[forge-1.18.2-40.2.0-universal.jar%2376!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:208) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%2371!/:?]
        ... 9 more
[04Jun2024 20:27:58.818] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: J0w03L lost connection: Internal server error
[04Jun2024 20:27:58.819] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: J0w03L left the game
[04Jun2024 20:27:58.829] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: iiJ0w03L lost connection: Internal server error
[04Jun2024 20:27:58.829] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: iiJ0w03L left the game
```

**Comment by J0w03L** [comment]
There does appear to be some safeguarding _somewhere_ based on behaviour in-game: trying to leash a regular player does nothing at all. Not 100% certain where this is, but however it's implemented doesn't work if the target is transfurred for whatever reason.

**Comment by LtxProgrammer** [comment]
It seems to be caused by [EntityMixin.java](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/master/src/main/java/net/ltxprogrammer/changed/mixin/entity/EntityMixin.java):83, where the changed mod will pass through the `interact()` function called on a player to their variant entity. The Leashed mod hooks into this `interact()` call to add the variant entity's UUID (same as the player's) to it's cache. When the mod attempts to look up that entity from the UUID, it gets the player instead.
